### PR TITLE
Fix of Warning: Illegal offset type in isset

### PR DESCRIPTION
**Pull request by mcambal**
Even though it would be better to use PHP7.1 type hints and rely on $id that is always integer. I'd like to propose this change to fix php warning error of isset($cacheData[$id]), when $id is array. This change also fixes bug of intval($id) (line: 165), because intval of array is null and improves performance, because it won't try to get data again from database.

### CODE REVIEW

**Comment by tomasnorre** [comment]
Thanks for you suggestion @mcambal, can you please look into why the tests are failing?

**Comment by mcambal** [comment]
@tomasnorre I checked that. I see as a problem issue with composer.json, where it requires for dev-master  the latest TYPO3 version which is 8 and Unit tests are compatible only with TYPO3 7. As a workaround I would changed that setting to TYPO3 7 in composer.json ("typo3/cms": ">=6.2.0 <8.0.0") Do you think that it is OK for you?

**Comment by tomasnorre** [comment]
That the dev-master fails is ok.

You will also see that in Travis. 
https://travis-ci.org/AOEpeople/languagevisibility/builds/249875272?utm_source=github_status&utm_medium=notification

But that they fail for 7.6 with PHP 5.5 we have to fix. 

Can you have a look at it?

**Comment by tomasnorre** [comment]
Looks like it was a hickup, just running the tests again.. If green i'll merge.

**Comment by tomasnorre** [comment]
Thanks a lot @mcambal

**Comment by mcambal** [comment]
You are welcome @tomasnorre ;)

**Pull request merged**
