### PR TITLE
[bug] Incorrect data type hint in hook

### PR DESCRIPTION
**Pull request by mcambal**

### CODE REVIEW

**Comment by mcambal** [comment]
@tomasnorre Merge please

**Comment by tomasnorre** [comment]
This will break 6.2 functionality, we will have to do some changes before that. 

We will take care in beginning of september.

**Comment by mcambal** [comment]
Doesn't make sense to create branch typo3 7, where particular typo3 7 changes take place? I thought that master is the latest development which supports typo3 7. The previous versions could be tagged. What is your thought on it?

**Comment by tomasnorre** [comment]
Could be a solution, but we need to do it clean. And we don't have the time before start of September. When i'm back from vacation. 

I don't like to have branches. The Master ist currently incorrect, that it says it supports 7 that we need to fix as well. 

If you need it early, you can always fork it and do you changes there and switch back when we are back on track, but we don't have time for a prober cleanup before start of september.

**Comment by tomasnorre** [comment]
Hi @mcambal 
Thanks for you "letter", unfortunately I was not in the Office to meet you in person. 

I will have a look at this asap, but as i'm not using this extension in my current project anymore, it's not that easy for me to priorities it. But as already written, i'll try to do this in the beginning of september. 

Please make a fork of it and use it till then.

**Comment by mcambal** [comment]
Yop, It was only joke. No rush. We use at the moment my forked version.

**Comment by tomasnorre** [comment]
All good :)

**Pull request closed without merging**
